// #region imports
    // #region libraries
    import {
        NewEntityField,
    } from '~kernel-components/NewEntityRenderer/data';
    // #endregion libraries
// #endregion imports



// #region module
export const fields: NewEntityField[] = [
    {
        label: 'name',
        type: 'string',
        state: 'name',
        value: 'new reaction',
        required: true,
    },
    {
        label: 'reaction zone',
        type: 'string',
        state: 'reactionZone',
        value: 'cell',
        required: true,
        help: `reaction zone identifier: 'cell' or 'mit'; where reaction takes place`,
    },
    {
        label: 'reactants',
        type: 'list',
        state: 'reactants',
        value: [ 'Substance_A' ],
        required: true,
        help: `list of reagents; must be from set of names defined for biomolecules in above`,
    },
    {
        label: 'reactant multipliers',
        type: 'list',
        state: 'reactantMultipliers',
        value: [ 1 ],
        required: true,
        help: `reaction coefficients for reagents, in same order as reagent definition`,
    },
    {
        label: 'Km reactants',
        type: 'list',
        state: 'KmReactants',
        value: [ 0.1 ],
        required: true,
        help: `list of half-max coefficients for reagents, in same order as reagents list`,
    },
    {
        label: 'products',
        type: 'list',
        state: 'products',
        value: [ 'Substance_A' ],
        required: true,
        help: `list of products; must be from set of names defined for biomolecules in above`,
    },
    {
        label: 'product multipliers',
        type: 'list',
        state: 'productMultipliers',
        value: [ 1 ],
        required: true,
        help: `reaction coefficients for products, in same order as product definition`,
    },
    {
        label: 'Km products',
        type: 'list',
        state: 'KmProducts',
        value: [ 0.1 ],
        required: true,
        help: `list of half-max coefficients for reagents, in same order as reagents list`,
    },
    {
        label: 'transfered out of cell',
        type: 'list',
        state: 'transferedOutOfCell',
        value: [],
        required: true,
        help: `items of reaction moved out of cell during forwards reaction`,
    },
    {
        label: 'transfered into cell',
        type: 'list',
        state: 'transferedIntoCell',
        value: [ 'Substance_A' ],
        required: true,
        help: `items of reaction moved into cell during forwards reaction`,
    },
    {
        label: 'max rate',
        type: 'number',
        state: 'maxRate',
        value: 1.0e-5,
        format: 'scientific',
        required: true,
        unit: 'mol/(m2*s)',
        help: `maximum rate of transport`,
    },
    {
        label: 'standard free energy',
        type: 'number',
        state: 'standardFreeEnergy',
        value: 0,
        format: 'float',
        required: true,
        unit: 'J/mol',
        help: `standard free energy of reaction in J/mol. 'None' creates non-reversible reaction`,
    },
    {
        label: 'apply to',
        type: 'list',
        state: 'applyTo',
        value: [ 'nerves', 'Spot' ],
        required: true,
        help: `apply transporter only on certain profiles`,
    },
    {
        label: 'ignore ECM',
        type: 'boolean',
        state: 'ignoreECM',
        value: true,
        required: true,
    },
    {
        label: 'transporter activators',
        type: 'string',
        state: 'transporterActivators',
        value: 'None',
        required: true,
        help: 'additional defined substances or ions increasing activity of transporter',
    },
    {
        label: 'activator Km',
        type: 'string',
        state: 'activatorKm',
        value: 'None',
        required: true,
    },
    {
        label: 'activator n',
        type: 'string',
        state: 'activatorN',
        value: 'None',
        required: true,
    },
    {
        label: 'transporter inhibitors',
        type: 'string',
        state: 'transporterInhibitors',
        value: 'None',
        required: true,
        help: 'additional defined substances or ions decreasing activity of transporter',
    },
    {
        label: 'inhibitor Km',
        type: 'string',
        state: 'inhibitorKm',
        value: 'None',
        required: true,
    },
    {
        label: 'inhibitor n',
        type: 'string',
        state: 'inhibitorN',
        value: 'None',
        required: true,
    },
];
// #endregion module
